@startuml





/' Objects '/

class Fruit {
	+Fruit(int row, int col, FruitEffect effect)
	+~Fruit()
	-effect : FruitEffect
	+GetCol() : int
	+GetEffect() : int
	+GetRow() : int
	-col : int
	-row : int
}


class MainSDLWindow {
	+MainSDLWindow()
	+~MainSDLWindow()
	+GetPlaygroundZone() : SDL_Rect
	+GetScoreZone() : SDL_Rect
	-playground : SDL_Rect
	-scoreZone : SDL_Rect
	+GetRenderer() : SDL_Renderer*
	-renderer : SDL_Renderer*
	-window : SDL_Window*
	+GetWindowHeight() : int
	+GetWindowWidth() : int
	+Init(const char* window_name, int width, int height) : int
}


class Playground {
	+Playground(int nbCols, int nbRows, Snake* snake)
	+~Playground()
	+GetFruit() : Fruit*
	-presentFruit : Fruit*
	+GetSnake() : Snake*
	-snake : Snake*
	+GetNbCols() : int
	+GetNbRows() : int
	-nbCols : int
	-nbRows : int
	+SetFruit(Fruit* newFruit) : void
	+SpawnFruit() : void
}


class PlaygroundRenderer {
	+PlaygroundRenderer()
	+~PlaygroundRenderer()
	-playground : Playground*
	-drawZone : SDL_Rect
	-renderer : SDL_Renderer*
	-bgTexture : SDL_Texture*
	+Init(SDL_Renderer* renderer, SDL_Rect drawZone, Playground* playground) : int
	-InitBackground() : int
	-tileHeight : int
	-tileWidth : int
	+draw(Playground* playground) : void
	-drawBackground() : void
	-drawFruit(Fruit* fruitToDraw) : void
	-drawSnake(Snake* snakeToDraw) : void
}


class Score {
	+Score()
	+~Score()
	+getNumberEaten() : int
	+getScore() : int
	-number_eaten : int
	-score : int
	+update_numb_eaten(int value) : void
	+update_score(int value) : void
}


class ScoreRenderer {
	+ScoreRenderer()
	+~ScoreRenderer()
	-drawZone : SDL_Rect
	-renderer : SDL_Renderer*
	-police : TTF_Font*
	+Init(SDL_Renderer* renderer, SDL_Rect drawZone) : int
	+draw(Score* score) : void
}


class Segment {
	+Segment(int row, int col, Direction direction, Segment* next)
	+~Segment()
	-direction : Direction
	+GetNext() : Segment*
	-next : Segment*
	+GetCol() : int
	+GetDirection() : int
	+GetRow() : int
	-col : int
	-row : int
	+SetDirection(Direction newDirection) : void
	+SetNext(Segment* nextSegment) : void
}


class Snake {
	+Snake(int starting_row, int starting_col, Direction starting_direction, int length)
	+~Snake()
	+GetHead() : Segment*
	-head : Segment*
	+Eat(Fruit* fruitToEat, Score* score, int* framerate) : bool
	+Move(Playground* playground, Score* score, int* framerate) : bool
	+occupiesTile(int row, int col) : bool
	+ChangeDirection(Direction newDirection) : void
}


enum Direction {
	DOWN
	LEFT
	RIGHT
	UP
}


enum FruitEffect {
	BONUS
	COUNT
	SHRINK
	SPEEDUP
}





/' Inheritance relationships '/




/' Aggregation relationships '/

.Fruit *-- .FruitEffect


.Playground o-- .Fruit


.Playground o-- .Snake


.PlaygroundRenderer o-- .Playground


.Segment *-- .Direction


.Segment o-- .Segment


.Snake o-- .Segment






/' Nested objects '/



@enduml

