@startuml
class MainSDLWindow{
  -SDL_Renderer* renderer
  -SDL_Window* window
  +MainSDLWindow()
  +~MainSDLWindow()
  +SDL_Renderer* : GenRenderer()
  +void WaitForClosing()
  +int Init(const char* window_name, int width, int height)
}
@enduml